parserOptions:
    ecmaVersion: 2020
    sourceType: module
    ecmaFeatures:
        jsx: true

env:
    browser: true
    es2020: true
    shared-node-browser: true

globals:
    require: false
    __DEBUG__: true
